name: Build and Publish to NuGet

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup .NET Core
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Specify your .NET version

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore
      
    # Build and pack
    - name: Build and pack
      run: dotnet pack --no-restore -c Release 

    # Publish the package to NuGet
    - name: Test key
      run: echo ${{secrets.NUGET_API_KEY}}
    - name: Publish to NuGet
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate --api-key "${{secrets.NUGET_API_KEY}}" --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Ensure this secret is set in your repository settings
